### ISSUE TITLE
IP-2416. App Logs > Allow to configure storage size 

### ISSUE THREAD

**Issue by idea2-pepito** [slingr-stack/pepito-test#1194]
In the account manager we should be able to configure the size of the logs for each environment. For now we can place that option below the database option. Later we will rearrange this screen to make it look better.

By default the size will be 100MB and the maximum allowed 10GB. This settings should be pass to the app (probably through the platform manager) and the app runtime should run a task to resize the logs collection (see the migration script Migration_20160429_AppLogsCollectionRestoreCappedConfigForGFS).

Change 1

Change 2

Change 3

Change 4

Change 5

Change 6

Change 7

**Comment by dgaviola** [comment]
test comment
